WIP: Remove support for servicemanager v2
zendframework/zend-mvc pull request #211
Opened 2016-12-22 20:13 UTC by snapshotpl

2016-12-22 20:43 UTC, snapshotpl commented
... and also zend-eventmanager v2.

2017-03-10 08:13 UTC, Xerkus requested changes
Great stuff, however there are couple BC concerns.

2017-03-10 08:13 UTC, Xerkus commented on src/Service/ServiceListenerFactory.php
> -            $this->injectV3Aliases();
breaking change, high chance someone still uses those compatibility aliases

2017-03-10 08:13 UTC, Xerkus commented on src/Service/ServiceListenerFactory.php
> -    private function injectV3Aliases()
breaking change, high chance someone still uses those compatibility aliases

2017-03-10 10:42 UTC, snapshotpl commented on src/Service/ServiceListenerFactory.php
> -            $this->injectV3Aliases();
@Xerkus you have right. That's why I add aliases into `$defaultServiceConfig` property (above)

2017-03-10 18:18 UTC, Xerkus approved these changes

2017-03-10 18:18 UTC, Xerkus commented on src/Service/ServiceListenerFactory.php
> -            $this->injectV3Aliases();
Indeed

2017-03-10 18:37 UTC, merged