Ensure proper PHPDoc and remove deprecated methods
zendframework/zend-mvc pull request #234
Opened 2017-04-27 15:27 UTC by boesing

Since always(?), the `AbstractActionController::notFoundAction` and the `AbstractActionController::indexAction` return `ViewModel`/`ConsoleModel` instead of `array`.

Aswell, I've removed deprecated methods which are already replaced by controller plugins aswell.

2017-04-27 16:52 UTC, weierophinney requested changes

2017-04-27 16:52 UTC, weierophinney commented on src/Controller/AbstractActionController.php
> -    protected function createHttpNotFoundModel(HttpResponse $response)
While these methods _should_ have been removed for the 3.0 release, they were not, and, as such, doing so now is a backwards compatibility break. Please create a separate PR for these removals which we can tag for the 4.0 release (which will target PHP 7.1).

Thanks!

2017-04-27 20:32 UTC, boesing commented on src/Controller/AbstractActionController.php
> -    protected function createHttpNotFoundModel(HttpResponse $response)
Actually they were removed in #99 
I will revert the commit on this for release-2.7 tho.

2017-05-01 15:34 UTC, merged

2017-05-01 15:34 UTC, weierophinney commented
Thanks, @boesing