[WIP] Fix: allow middleware dispatch to behave like controller dispatch
zendframework/zend-mvc pull request #236
Opened 2017-04-28 13:53 UTC by Ocramius

This patch makes sure that the successful dispatch of a middleware won't trigger exception and 404 strategies. This can happen when the return value of the `MiddlewareListener` is not a `Zend\Stdlib\ResponseInterface` instance, and therefore the `EventManager` will not short-circuit and stop event propagation. This allows returning anything from a configured `middleware`:

 * `['foo' => 'bar']`
 * `'Hello World!'`
 * `new ViewModel(['foo' => 'bar'])`

This also fixes https://github.com/zendframework/zendframework/issues/5806

I'm still stuck on this though. As per tradition `Zend\Mvc\ViewManager` is being absolutely useless, and [attaches all listeners to the shared manager `DispatchableInterface` identifier](https://github.com/zendframework/zend-mvc/blob/2c64d2ed50063e13b23f1c7e19f17ce3354bea36/src/View/Http/ViewManager.php#L124-L152): that means that basically nothing in the view layer works when using this stuff.

Currently preparing a workaround that triggers events that have the `DispatchableInterface` identifier, since otherwise it is impossible to get this thing running correctly.

2017-04-28 15:05 UTC, Ocramius commented on src/MiddlewareListener.php
> +        $event->setError('');
Note: this still means that the `DispatchListener` will try to execute and fail. The patch is not yet done. Ideally, the `DispatchListener` should check whether there is a `$event->getResult()`, and bail out if there already is one.

2017-05-01 16:57 UTC, weierophinney requested changes
I like this approach a ton; I think triggering events for dispatched middleware in the same way as for controllers could have a ton of benefits.

A few comments:

- This is technically new functionality (new class), and I think it would be best to do for the 3.1.0 release. As such, you'd need to rebase against develop... which has a number of changes due to me merging #217 earlier today. I'd be happy to help with that if you wish.
- The `MiddlewareController` should also allow http-interop middleware; I have detailed comments on that below.
- I agree that this and the `DispatchListener` should return early if the `MvcEvent` composes a result already, and think that change should be part of this PR (as this PR is the one that demonstrates the need for that change).

2017-05-01 16:57 UTC, weierophinney commented on src/MiddlewareListener.php
> +        $event->setError('');
I'd argue both the `DispatchListener` and `MiddlewareListener` should act that way, with the following at the top of the listeners:

```php
if (null !== $e->getResult()) {
    return;
}
```

Do you want to incorporate that change in this PR?

2017-05-01 16:57 UTC, weierophinney commented on src/Controller/MiddlewareController.php
> +    public function __construct(callable $middleware, EventManager $eventManager, MvcEvent $event)
Just a note: on the develop branch, we're now targeting Stratigility `^2.0.1`, which means we can have:

- callable middleware
- http-interop middleware

If this patch targets master, we would need to remove the typehint for `$middleware`, and also update how middleware is invoked based on whether or not it implements `Interop\Http\ServerMiddleware\MiddlewareInterface`.

2017-05-01 16:57 UTC, weierophinney commented on src/Controller/MiddlewareController.php
> +        $result = \call_user_func($this->middleware, $psr7Request, Psr7Response::fromZend($response));
See previous note about http-interop.

2017-05-01 16:57 UTC, weierophinney commented on test/MiddlewareListenerTest.php
> +            die(var_dump($e->getParam('exception')->getMessage()));
Um, `die()`? Why not just a `var_dump()` or capturing that info to a variable to emit with the `fail()` below?

2017-05-01 18:25 UTC, Ocramius commented on src/MiddlewareListener.php
> +        $event->setError('');
@weierophinney done for both listeners

2017-05-01 18:25 UTC, Ocramius commented on test/MiddlewareListenerTest.php
> +            die(var_dump($e->getParam('exception')->getMessage()));
This is also gone :-)

2017-05-01 18:33 UTC, Ocramius commented
> This is technically new functionality (new class), and I think it would be best to do for the 3.1.0 release. As such, you'd need to rebase against develop... which has a number of changes due to me merging #217 earlier today. I'd be happy to help with that if you wish.

Provided

 > The `MiddlewareController` should also allow http-interop middleware; I have detailed comments on that below.

That's also handled. The `MiddlewareController`, being an internal class, can be changed as much as it suits us.

 > I agree that this and the `DispatchListener` should return early if the `MvcEvent` composes a result already, and think that change should be part of this PR (as this PR is the one that demonstrates the need for that change).

Implemented/tested

2017-05-01 19:06 UTC, Ocramius commented on src/Controller/MiddlewareController.php
> +        ResponseInterface $responsePrototype,
Not particularly proud of this, but PSR-7's immutability makes it quite acceptable to pass in a request as a prototype. Still, this class is designed as "fire once" and "internal" specifically due to this weirdness.

2017-05-01 20:18 UTC, merged